---
name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      stack:
        type: choice
        required: true
        description: The AWS Stack to deploy.
        options:
          - Development
          - Master
          - Release

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - name: Install dependencies
        run: cd .. && npm install
