---
name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      stack:
        type: choice
        required: true
        description: The AWS Stack to deploy.
        options:
          - Development
          - Master
          - Release

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Deployment
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g aws-cdk && pip3 install -r requirements.txt
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-session-name: GithubRunnerDeployment
      - name: Bootstrap environment
        run: cdk bootstrap
      - name: Synthesize stack
        run: cdk synth ${{ format('SampleImage{0}', github.event.inputs.stack) }}
      - name: Deploy stack
        run: cdk deploy --require-approval never ${{ format('SampleImage{0}', github.event.inputs.stack) }}