---
name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      stack:
        type: choice
        required: true
        description: The AWS Stack to deploy.
        options:
          - Development
          - Master
          - Release

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Deployment
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g aws-cdk
      - name: Bootstrap environment
        run: cdk bootstrap
      - name: Synthesize stack
        run: cdk synth SampleImage
      - name: Deploy stack
        run: cdk deploy SampleImage${{github.event.inputs.stack}}