---
name: Push Development Image

on:
  pull_request:
    branches:
      - feature/**
      - bugfix/**
      - enhancement/**
      - demo/**

jobs:
  Push:
    runs-on: ubuntu-latest
    environment: Development
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ECR_REGISTRY_ARN: ${{ secrets.AWS_ECR_REGISTRY_ARN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
      - name: Install dependencies
        run: pip3 install awscli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: $AWS_DEFAULT_REGION
          role-to-assume: $AWS_ROLE_ARN
          role-session-name: GithubDevelopmentPush
      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build image
        run: docker build docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG .
      - name: Push image
        run: docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG
